# Generated by Django 4.0.1 on 2022-06-20 12:29

import api.order.models_validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('payments', '0001_initial'), ('payments', '0002_commission_closing_order_datetime'), ('payments', '0003_remove_commission_master_commission_master'), ('payments', '0004_alter_commission_amount'), ('payments', '0005_alter_commission_closing_order_datetime')]

    initial = True

    dependencies = [
        ('master', '0004_remove_master_middle_name'),
        ('order', '0012_alter_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, null=True, validators=[api.order.models_validators.validate_positive_number], verbose_name='Commission amount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_commission', to='order.order', verbose_name='Order')),
                ('closing_order_datetime', models.DateTimeField(auto_now_add=True, default='2022-04-21T17:47:00+01:00', verbose_name='Closing order date')),
                ('master', models.ManyToManyField(related_name='master_commission', to='master.Master', verbose_name='Master')),
            ],
        ),
    ]
