# Generated by Django 4.0.1 on 2022-05-18 15:45

import api.order.models_validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0012_alter_order_address'),
        ('master', '0004_remove_master_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[api.order.models_validators.validate_positive_number], verbose_name='Commission amount')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_commission', to='master.master', verbose_name='Master')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_commission', to='order.order', verbose_name='Order')),
            ],
        ),
    ]
