# Generated by Django 4.0.1 on 2022-06-21 18:32

import api.order.models_validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, null=True, validators=[api.order.models_validators.validate_positive_number], verbose_name='Commission amount')),
                ('closing_order_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Closing order date')),
                ('master', models.ManyToManyField(related_name='master_commission', to='master.Master', verbose_name='Master')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_commission', to='order.order', verbose_name='Order')),
            ],
        ),
    ]
