# Generated by Django 4.0.1 on 2022-05-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='closing_order_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closing order date'),
        ),
    ]
