# Generated by Django 4.0.1 on 2022-06-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_commission_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='closing_order_datetime',
            field=models.DateTimeField(auto_now_add=True, default='2022-04-21T17:47:00+01:00', verbose_name='Closing order date'),
            preserve_default=False,
        ),
    ]
