# Generated by Django 4.0.1 on 2022-02-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='work start time'),
        ),
    ]
