# Generated by Django 4.0.1 on 2022-03-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_orderfile_file_remove_orderfile_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9, verbose_name='latitude in degrees'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9, verbose_name='longitude in degrees'),
            preserve_default=False,
        ),
    ]
