# Generated by Django 4.0.1 on 2022-04-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default=1, max_length=150, verbose_name='middle name'),
            preserve_default=False,
        ),
    ]
