# Generated by Django 4.0.1 on 2022-06-21 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivateAccountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField(verbose_name='activate code')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('last_resend_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Last resend code datetime')),
                ('number_resending', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of resending code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activate_code_user', to=settings.AUTH_USER_MODEL, verbose_name='activate code for user')),
            ],
            options={
                'verbose_name': 'Activate Account Code',
            },
        ),
    ]
