# Generated by Django 4.0.1 on 2022-06-20 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('authenticate', '0001_initial'), ('authenticate', '0002_alter_activateaccountcode_options'), ('authenticate', '0003_activateaccountcode_number_resending'), ('authenticate', '0004_activateaccountcode_last_resend_datetime'), ('authenticate', '0005_alter_activateaccountcode_last_resend_datetime'), ('authenticate', '0006_alter_activateaccountcode_last_resend_datetime'), ('authenticate', '0007_remove_activateaccountcode_created_datetime_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivateAccountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField(verbose_name='activate code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activate_code_user', to=settings.AUTH_USER_MODEL, verbose_name='activate code for user')),
                ('number_resending', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of resending code')),
                ('last_resend_datetime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Last resend code datetime')),
                ('created_date', models.DateField(auto_now_add=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Activate Account Code',
            },
        ),
    ]
