# Generated by Django 4.0.1 on 2022-04-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activateaccountcode',
            options={'verbose_name': 'Activate Account Code'},
        ),
    ]
