# Generated by Django 4.0.1 on 2022-06-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_squashed_0007_remove_activateaccountcode_created_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activateaccountcode',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
