# Generated by Django 4.0.1 on 2022-04-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_activateaccountcode_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='activateaccountcode',
            name='number_resending',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of resending code'),
        ),
    ]
