# Generated by Django 4.0.1 on 2022-04-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_activateaccountcode_number_resending'),
    ]

    operations = [
        migrations.AddField(
            model_name='activateaccountcode',
            name='last_resend_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last resend code datetime'),
        ),
    ]
