# Generated by Django 4.0.1 on 2022-04-29 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_alter_activateaccountcode_last_resend_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activateaccountcode',
            name='last_resend_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Last resend code datetime'),
        ),
    ]
