# Generated by Django 4.0.1 on 2022-03-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
    ]
