# Generated by Django 4.0.1 on 2022-03-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9, verbose_name='latitude in degrees'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='master',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9, verbose_name='longitude in degrees'),
            preserve_default=False,
        ),
    ]
