# Generated by Django 4.0.1 on 2022-06-21 18:32

import api.order.models_validators
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types_of_work', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None, verbose_name='Work type')),
                ('number_employees', models.PositiveIntegerField(validators=[api.order.models_validators.validate_less_then_ninety], verbose_name='Employees number')),
                ('desired_time_end_work', models.PositiveIntegerField(validators=[api.order.models_validators.validate_less_then_ninety], verbose_name='Work duration')),
                ('start_time', models.DateTimeField(verbose_name='work start time')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[api.order.models_validators.validate_positive_number], verbose_name='Order price')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Order description')),
                ('address', models.CharField(max_length=256, verbose_name='Order address')),
                ('city', models.CharField(max_length=100, verbose_name='Order city')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude in degrees')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude in degrees')),
                ('status', models.CharField(choices=[('SEARCH_MASTER', 'Поиск мастера'), ('AWAIT_EXECUTING', 'Ожидает выполнения'), ('CANCELED', 'Заявка отменена'), ('DONE', 'Заявка выполнена')], default='Поиск мастера', max_length=30, verbose_name='Order status')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_customer', to=settings.AUTH_USER_MODEL)),
                ('master', models.ManyToManyField(blank=True, related_name='order_master', to='master.Master', verbose_name='Order masters')),
                ('work_sphere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_work_sphere', to='master.worksphere', verbose_name='order work sphere')),
            ],
            options={
                'verbose_name': 'Order',
            },
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_path', models.CharField(max_length=1056, verbose_name='Bucket path')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_files', to='order.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order File',
            },
        ),
    ]
