# Generated by Django 4.0.1 on 2022-06-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_squashed_0012_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start_time',
            field=models.DateTimeField(verbose_name='work start time'),
        ),
    ]
