# Generated by Django 4.0.1 on 2022-03-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='city of the order'),
            preserve_default=False,
        ),
    ]
