# Generated by Django 4.0.1 on 2022-04-01 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('order', '0002_order_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_master', to='master.master', verbose_name='Order master'),
        ),
    ]
