# Generated by Django 4.0.1 on 2022-04-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('order', '0003_order_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='master',
        ),
        migrations.AddField(
            model_name='order',
            name='master',
            field=models.ManyToManyField(blank=True, null=True, related_name='order_master', to='master.Master', verbose_name='Order master'),
        ),
    ]
