# Generated by Django 4.0.1 on 2022-04-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('order', '0004_remove_order_master_order_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='master',
            field=models.ManyToManyField(blank=True, related_name='order_master', to='master.Master', verbose_name='Order master'),
        ),
    ]
