# Generated by Django 4.0.1 on 2022-04-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start_time',
            field=models.DateTimeField(default='2022-04-03T00:00:00+01:00', verbose_name='work start time'),
            preserve_default=False,
        ),
    ]
