# Generated by Django 4.0.1 on 2022-04-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('SEARCH_MASTER', 'Поиск мастера'), ('AWAIT_EXECUTING', 'Ожидает выполнения'), ('ORDER_REJECTED', 'Заявка отклонена'), ('ORDER_CUSTOMER_CANCELED', 'Заявка отменена клиентом'), ('ORDER_MASTER_CANCELED', 'Заявка отменена мастером'), ('PAID', 'Оплачено')], default='Поиск мастера', max_length=30),
        ),
    ]
