# Generated by Django 4.0.1 on 2022-04-19 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_worksphere_remove_master_work_experience_and_more'),
        ('order', '0006_alter_order_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='work_sphere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_work_sphere', to='master.worksphere', verbose_name='order work sphere'),
        ),
        migrations.DeleteModel(
            name='WorkSphere',
        ),
    ]
