# Generated by Django 4.0.1 on 2022-04-22 08:40

import api.order.models_validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_worksphere_remove_master_work_experience_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0007_alter_order_work_sphere_delete_worksphere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Address of the customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Description of order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='desired_time_end_work',
            field=models.CharField(max_length=40, verbose_name='Work duration'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Order name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='number_employees',
            field=models.PositiveIntegerField(validators=[api.order.models_validators.validate_less_then_forty], verbose_name='number of employees'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Order price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='work_sphere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_work_sphere', to='master.worksphere', verbose_name='order work sphere'),
        ),
    ]
