# Generated by Django 4.0.1 on 2022-04-18 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_worksphere_remove_master_work_experience_and_more'),
        ('order', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('SEARCH_MASTER', 'Поиск мастера'), ('AWAIT_EXECUTING', 'Ожидает выполнения'), ('CANCELED', 'Заявка отменена'), ('PAID', 'Оплачено')], default='Поиск мастера', max_length=30),
        ),
        migrations.CreateModel(
            name='OrderMasterStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REJECTED', 'Заявка отклонена'), ('CUSTOMER_CANCELED', 'Заявка отменена клиентом'), ('MASTER_CANCELED', 'Заявка отменена мастером'), ('MASTER_FOUND', 'Мастер найден'), ('ACCEPTED', 'Заявка принята')], max_length=30)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_order_status', to='master.master', verbose_name='Master for order status')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_master_status', to='order.order', verbose_name='Order for master status')),
            ],
        ),
    ]
