# Generated by Django 4.0.1 on 2022-04-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_status_ordermasterstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermasterstatus',
            name='status',
            field=models.CharField(choices=[('REJECTED', 'Заявка отклонена'), ('CUSTOMER_CANCELED', 'Заявка отменена клиентом'), ('MASTER_CANCELED', 'Заявка отменена мастером'), ('ACCEPTED', 'Заявка принята')], max_length=30),
        ),
    ]
