# Generated by Django 4.0.1 on 2022-04-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_address_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='orderfile',
            options={'verbose_name': 'Order File'},
        ),
        migrations.AlterModelTable(
            name='orderfile',
            table=None,
        ),
    ]
