# Generated by Django 4.0.1 on 2022-04-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_options_alter_orderfile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('SEARCH_MASTER', 'Поиск мастера'), ('AWAIT_EXECUTING', 'Ожидает выполнения'), ('CANCELED', 'Заявка отменена'), ('PAID', 'Оплачено')], default='SEARCH_MASTER', max_length=30),
        ),
    ]
