# Generated by Django 4.0.1 on 2022-04-26 21:18

import api.order.models_validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_master_middle_name'),
        ('order', '0010_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default=1, max_length=256, verbose_name='Client address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Order city'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Order description'),
        ),
        migrations.AlterField(
            model_name='order',
            name='master',
            field=models.ManyToManyField(blank=True, related_name='order_master', to='master.Master', verbose_name='Order masters'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number_employees',
            field=models.PositiveIntegerField(validators=[api.order.models_validators.validate_less_then_forty], verbose_name='Employees number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[api.order.models_validators.validate_positive_number], verbose_name='Order price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('SEARCH_MASTER', 'Поиск мастера'), ('AWAIT_EXECUTING', 'Ожидает выполнения'), ('CANCELED', 'Заявка отменена'), ('DONE', 'Заявка выполнена')], default='Поиск мастера', max_length=30, verbose_name='Order status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='types_of_work',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None, verbose_name='Work type'),
        ),
    ]
