# Generated by Django 4.0.1 on 2022-06-20 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('master', '0001_initial'), ('master', '0002_worksphere_remove_master_work_experience_and_more'), ('master', '0003_master_middle_name'), ('master', '0004_remove_master_middle_name')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSphere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='work sphere name')),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude in degrees')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude in degrees')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='MasterExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.PositiveIntegerField(verbose_name='experience')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_experience', to='master.master', verbose_name='Master')),
                ('work_sphere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sphere', to='master.worksphere', verbose_name='Work Sphere')),
            ],
        ),
    ]
