# Generated by Django 4.0.1 on 2022-04-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSphere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='work sphere name')),
            ],
        ),
        migrations.RemoveField(
            model_name='master',
            name='work_experience',
        ),
        migrations.CreateModel(
            name='MasterExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.PositiveIntegerField(verbose_name='experience')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_experience', to='master.master', verbose_name='Master')),
                ('work_sphere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sphere', to='master.worksphere', verbose_name='Work Sphere')),
            ],
        ),
    ]
