# Generated by Django 4.0.1 on 2022-04-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_worksphere_remove_master_work_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='middle_name',
            field=models.CharField(default=1, max_length=150, verbose_name='middle name'),
            preserve_default=False,
        ),
    ]
